on: issue_comment

jobs:
  issue_commented:
    name: PR comment
    if: ${{ github.event.comment.body == '/format' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Format..."
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            **Formatted!**
            ğŸŒ
            !
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default